general:
  device: "cuda"
  pause_type: "silence"
  sample_rate: 22050

natasha:
  voice_control_cfg: data/natasha/voice_natasha.yaml
  user_dict: data/natasha/natasha_user_dict.json

  text_handler:
    config_path: data/text_handler_config.yaml
    out_max_length: 200
    dict_source: data/user_dict.json

  modules:
    engine: tacotron2
    vocoder: waveglow

  engine:
    tacotron2:
      model_path: data/natasha/checkpoint_natasha
      hparams_path: data/natasha/hparams_natasha.yaml
      options:
        max_decoder_steps: 1500
        gate_threshold: 0.5

  vocoder:
    waveglow:
      model_path: data/natasha/waveglow_ljs_nvidia.pt
      options:
        sigma: 0.666
        strength: 0.1

ruslan:
  voice_control_cfg: data/ruslan/voice_ruslan.yaml
  user_dict: data/ruslan/ruslan_user_dict.json

  text_handler:
    config_path: data/text_handler_config.yaml
    out_max_length: 200
    dict_source: data/user_dict.json

  modules:
    engine: tacotron2
    vocoder: waveglow

  engine:
    tacotron2:
      model_path: data/ruslan/checkpoint_ruslan
      hparams_path: data/ruslan/hparams_ruslan.yaml
      options:
        max_decoder_steps: 1500
        gate_threshold: 0.5

  vocoder:
    waveglow:
      model_path: data/ruslan/waveglow_ruslan.pt
      options:
        sigma: 0.666
        strength: 0.1